git:
  branchLogCmd: "git log --format=format:\"%C(blue)%as %C(auto)%h %C(green)%aN%Creset %s\""
  paging:
    colorArg: never
    pager: delta --light --paging=never
gui:
  showIcons: true
  theme:
    lightTheme: true
    selectedLineBgColor:
      - '#EEE8D5'
    cherryPickedCommitBgColor:
      - '#EEE8D5'
customCommands:
  - key: "M"
    command: "nvim . -c \"DiffviewOpen\""
    context: "files"
    loadingText: "Opening vim merge tool"
    subprocess: true
