git:
  branchLogCmd: "git log --format=format:\"%C(blue)%as %C(auto)%h %C(green)%aN%Creset %s\""
  paging:
    colorArg: never
    pager: delta --light --paging=never
gui:
  showIcons: true
  theme:
    lightTheme: false 
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red       # Red
customCommands:
  - key: "M"
    command: "nvim . -c \"DiffviewOpen\""
    context: "files"
    loadingText: "Opening vim merge tool"
    subprocess: true
